<a href="https://colab.research.google.com/github/keerthanamjohn3-arch/git.demo/blob/main/CNN2_mask_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from skimage.io import imread
from skimage.transform import resize
import os
from keras.models import Sequential
from keras.layers import Conv2D,MaxPool2D,Dense,Flatten

In [2]:
train_path = "/content/drive/MyDrive/Maskdata"


X_train = []
y_train = []

categories = os.listdir(train_path)
# print(categories)

for category in categories:
  cat_path = os.path.join(train_path,category)
  print(cat_path)

  images = os.listdir(cat_path)
  # print(images)

  for img in images:
    img_path = os.path.join(cat_path,img)
    image = imread(img_path)

    img_resize = resize(image,(150,150,3))

    X_train.append(img_resize)
    y_train.append(categories.index(category))

  print(category,"Loaded.........")



/content/drive/MyDrive/Maskdata/without_mask
without_mask Loaded.........
/content/drive/MyDrive/Maskdata/with_mask


/usr/local/lib/python3.12/dist-packages/PIL/Image.py:1047: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


with_mask Loaded.........


In [3]:
test_path = "/content/drive/MyDrive/Maskdatatest"

X_test = []
y_test = []

for category in categories:
  cat_path = os.path.join(test_path,category)
  images = os.listdir(cat_path)

  for img in images:
    img_path = os.path.join(cat_path,img)
    image = imread(img_path)

    img_resize = resize(image,(150,150,3))
    X_test.append(img_resize)
    y_test.append(categories.index(category))
  print(category,"Loaded.........")


without_mask Loaded.........
with_mask Loaded.........


In [ ]:
len(X_train),len(y_train)


In [5]:
len(X_test),len(y_test)

(102, 102)

In [6]:
import numpy as np
X_train = np.array(X_train)
X_test  = np.array(X_test)
y_test = np.array(y_train)
y_train = np.array(y_test)

In [7]:
X_train.shape

(3150, 150, 150, 3)

In [8]:
model = Sequential()
model.add(Conv2D(32,(3,3),input_shape =(150,150,3),activation = 'relu'))
model.add(MaxPool2D())
model.add(Flatten())
model.add(Dense(100,activation = 'relu'))
model.add(Dense(2,activation = 'softmax'))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.compile(optimizer = 'adam',loss  = 'sparse_categorical_crossentropy',metrics = ['accuracy'])

In [10]:
model.fit(X_train,y_train,epochs = 50,batch_size =12)

Epoch 1/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - accuracy: 0.7663 - loss: 1.0186
Epoch 2/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9357 - loss: 0.1708
Epoch 3/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9741 - loss: 0.0835
Epoch 4/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9768 - loss: 0.0698
Epoch 5/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9702 - loss: 0.0897
Epoch 6/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9870 - loss: 0.0416
Epoch 7/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9928 - loss: 0.0308
Epoch 8/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9841 - loss: 0.0463
Epoch 9/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9940 - loss: 0.0164
Epoch 10/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9974 - loss: 0.0084
Epoch 11/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9900 - loss: 0.0349
Epoch 12/50
263/263 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/

In [ ]:
model.evaluate(X_test,y_test)

In [12]:
model.save('mask_data.keras')

In [13]:
y_pred = model.predict(X_test)
y_pred

4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 435ms/step


array([[1.00000000e+00, 2.35053643e-10],
       [1.00000000e+00, 3.07200142e-12],
       [9.99999881e-01, 1.01102003e-07],
       [1.00000000e+00, 4.68293547e-17],
       [1.00000000e+00, 5.91974505e-08],
       [1.00000000e+00, 1.83524352e-16],
       [1.00000000e+00, 6.13338278e-17],
       [1.00000000e+00, 2.49075732e-10],
       [2.34241322e-01, 7.65758753e-01],
       [1.00000000e+00, 3.75244020e-12],
       [1.00000000e+00, 1.09553290e-13],
       [1.00000000e+00, 1.18434660e-19],
       [1.00000000e+00, 1.89023146e-12],
       [7.19494939e-01, 2.80505031e-01],
       [1.00000000e+00, 2.47863924e-10],
       [1.00000000e+00, 2.00251556e-12],
       [1.00000000e+00, 1.18737627e-21],
       [9.99994159e-01, 5.87364866e-06],
       [9.99998927e-01, 1.03771015e-06],
       [1.00000000e+00, 2.03841430e-10],
       [1.00000000e+00, 4.65450151e-10],
       [9.99999881e-01, 7.92805324e-08],
       [1.00000000e+00, 5.30668402e-32],
       [1.00000000e+00, 1.10130552e-23],
       [9.999997

In [14]:
y_pred1 = y_pred.argmax(axis = 1)
y_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0])

In [15]:
y_test

array([0, 0, 0, ..., 1, 1, 1])